kind: Service
apiVersion: v1
metadata:
  name: api
  namespace: default
  selfLink: /api/v1/namespaces/default/services/api
  uid: bf96179b-d431-4e3a-a069-dfe279fcda3a
  creationTimestamp: '2021-02-26T12:57:22Z'
  labels:
    k8s-app: api
spec:
  ports:
    - name: tcp-3001-3001-522m5
      protocol: TCP
      port: 3001
      targetPort: 3001
  selector:
    k8s-app: api
  # clusterIP: 10.0.149.105
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}