kind: Deployment
apiVersion: apps/v1
metadata:
  name: api
  namespace: default
  selfLink: /apis/apps/v1/namespaces/default/deployments/api
  uid: 4aa6707e-0414-4e3e-9365-a96032b94d0b
  generation: 1
  creationTimestamp: '2021-02-26T12:57:22Z'
  labels:
    k8s-app: api
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: api
  template:
    metadata:
      name: api
      creationTimestamp: null
      labels:
        k8s-app: api
    spec:
      containers:
        - name: api
          image: acr318699.azurecr.io/content-api
          env:
          - name: MONGODB_CONNECTION
            valueFrom:
              secretKeyRef:
                name: cosmosdb
                key: db
          resources:
            requests:
              cpu: '250m'
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  unavailableReplicas: 1
  conditions:
    - type: Available
      status: 'False'
      lastUpdateTime: '2021-02-26T12:57:22Z'
      lastTransitionTime: '2021-02-26T12:57:22Z'
      reason: MinimumReplicasUnavailable
      message: Deployment does not have minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2021-02-26T12:57:22Z'
      lastTransitionTime: '2021-02-26T12:57:22Z'
      reason: ReplicaSetUpdated
      message: ReplicaSet "api-f87d48665" is progressing.
